### ISSUE TITLE
Does this support Django 1.8 ?

### ISSUE THREAD

**Issue by muzaffaryousaf** [EnTeQuAk/django-babel-underscore#3]
Right now, i can see in setup.py that it provide support only for 1.4 < Django < 1.8 ? 
Any plans to add support for Django 1.8 . 

Thanks

**Comment by EnTeQuAk** [comment]
Hey @muzaffaryousaf and sorry for the late reply. It's fixed now in `0.4.1` and should work just fine.

**Comment by muzaffaryousaf** [comment]
Thanks a lot..
